ProduktOhneNutzDaten:
  type: object
  xml:
    name: 'Produkt'
  required:
    - id
    - version
    - name
  properties:
    id:
      type: string
      xml:
        attribute: true
    version:
      type: string
      xml:
        attribute: true
    name:
      type: string
      xml:
        attribute: true
    SchnittstellenQuellproduktRef:
      type: object
      nullable: true
      xml:
        name: 'SchnittstellenQuellproduktRef'
      properties:
        id:
          $ref: './Produkt.yaml#/Produkt/properties/id'
        name:
          $ref: './Produkt.yaml#/Produkt/properties/name'
    TextbausteinRef:
      type: object
      nullable: true
      xml:
        name: 'TextbausteinRef'
      properties:
        id:
          $ref: './Textbaustein.yaml#/Textbaustein/properties/id'
        name:
          $ref: './Textbaustein.yaml#/Textbaustein/properties/name'